### ISSUE TITLE
msg=TypeError: Cannot read property 'findOne' of undefined

### ISSUE THREAD

**Issue by mausquirk** [telefonicaid/iotagent-json#252]
I'm working through the [Step-by-Step-guide](https://github.com/telefonicaid/iotagent-json/blob/master/docs/stepbystep.md) and got stuck on the [Provisioning](https://github.com/telefonicaid/iotagent-json/blob/master/docs/stepbystep.md#provisioning-the-device)-Step:

The iotagent logs: 

> time=2017-12-13T15:38:45.437Z | lvl=DEBUG | corr=98187582-d965-4a75-a8f5-f4f42a9cc734 | trans=98187582-d965-4a75-a8f5-f4f42a9cc734 | op=IoTAgentNGSI.GenericMiddlewares | srv=myHome | subsrv=/environment | msg=Request for path [/iot/devices] from [orion:4041] | comp=IoTAgent
> time=2017-12-13T15:38:45.440Z | lvl=DEBUG | corr=98187582-d965-4a75-a8f5-f4f42a9cc734 | trans=98187582-d965-4a75-a8f5-f4f42a9cc734 | op=IoTAgentNGSI.GenericMiddlewares | srv=myHome | subsrv=/environment | msg=Body:
> 
> {
>     "devices": [
>         {
>             "device_id": "sensor01",
>             "entity_name": "LivingRoomSensor",
>             "entity_type": "multiSensor",
>             "attributes": [
>                 {
>                     "object_id": "t",
>                     "name": "Temperature",
>                     "type": "celsius"
>                 },
>                 {
>                     "object_id": "l",
>                     "name": "Luminosity",
>                     "type": "lumens"
>                 }
>             ]
>         }
>     ]
> }
> 
>  | comp=IoTAgent
> time=2017-12-13T15:38:45.445Z | lvl=DEBUG | corr=98187582-d965-4a75-a8f5-f4f42a9cc734 | trans=98187582-d965-4a75-a8f5-f4f42a9cc734 | op=IoTAgentNGSI.DeviceProvisioning | srv=myHome | subsrv=/environment | msg=Handling device provisioning request. | comp=IoTAgent
> time=2017-12-13T15:38:45.448Z | lvl=DEBUG | corr=98187582-d965-4a75-a8f5-f4f42a9cc734 | trans=98187582-d965-4a75-a8f5-f4f42a9cc734 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=myHome | subsrv=/environment | msg=Looking for entity params undefined | comp=IoTAgent
> time=2017-12-13T15:38:45.451Z | lvl=ERROR | corr=98187582-d965-4a75-a8f5-f4f42a9cc734 | trans=98187582-d965-4a75-a8f5-f4f42a9cc734 | op=IoTAgentNGSI.DomainControl | srv=myHome | subsrv=/environment | msg=TypeError: Cannot read property 'findOne' of undefined | comp=IoTAgent
> time=2017-12-13T15:38:45.452Z | lvl=DEBUG | corr=98187582-d965-4a75-a8f5-f4f42a9cc734 | trans=98187582-d965-4a75-a8f5-f4f42a9cc734 | op=IoTAgentNGSI.DomainControl | srv=myHome | subsrv=/environment | msg=response-time: 18 | comp=IoTAgent
> 

Note the line:
> time=2017-12-13T15:38:45.451Z | lvl=ERROR | corr=98187582-d965-4a75-a8f5-f4f42a9cc734 | trans=98187582-d965-4a75-a8f5-f4f42a9cc734 | op=IoTAgentNGSI.DomainControl | srv=myHome | subsrv=/environment | msg=TypeError: Cannot read property 'findOne' of undefined | comp=IoTAgent

My docker-compose.yml:
```
mongodb:
  image: mongo:3.2
  hostname: mongodb
  container_name: mongodb
  command: --nojournal
  expose:
    - "27017"
  ports:
    - "27017:27017"
  volumes:
    - ./data/mongodb:/data/db
 
orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    links:
        - mongodb
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost mongodb

iot-agent-mqtt:
    image: telefonicaiot/iotagent-json
    hostname: iotagent
    container_name: iotagent
    links:
        - orion
        - mongodb
    expose:
        - "4041"
    ports:
        - "4041:4041"

mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto 
    container_name: mosquitto
    links:
        - iot-agent-mqtt
    expose:
        - "1883"
    ports:
        - "1883:1883"
```
There is no ito-agent database created in the mongo-db.
