### ISSUE TITLE
error connecting to the Context Broker [404] 

### ISSUE THREAD

**Issue by abdenour1996** [telefonicaid/iotagent-json#470]
I am using Docker containers for linking Scorpio Broker, Postgres, IoT Agent for JSON and Mosquitto Broker.
All the containers start correctly.
this is the .yml file :

````   
version: '2'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  postgres:
    image: mdillon/postgis
    hostname: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  scorpio:
    image: scorpiobroker/scorpio:scorpio-aaio_0.9.7
    hostname: scorpio
    ports:
      - "9090:9090"
    depends_on:
      - kafka
      - postgres
  iotagent:
    image: fiware/iotagent-json
    hostname: iotagent
    container_name: fiware-iot-agent
    depends_on:
       - postgres
    expose:
       - "4041"
       - "7896"
    ports:
       - "4041:4041"
       - "7896:7896"
    environment:
       - "IOTA_CB_HOST=scorpio"
       - "IOTA_CB_PORT=9090"
       - "IOTA_CB_NGSI_VERSION=v2"
       - "IOTA_NORTH_PORT=4041"
       - "IOTA_REGISTRY_TYPE=postgres"
       - "IOTA_POSTGRES_HOST=postgres"
       - "IOTA_POSTGRES_PORT=5432"
       - "IOTA_POSTGRES_DB=ngb"
       - "IOTA_HTTP_PORT=7896"
       - "IOTA_MQTT_HOST=mosquitto"
       - "IOTA_MQTT_PORT=1883"
       - "IOTA_PROVIDER_URL=http://iot-agent:4041"
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    networks:
        - default
    expose:
        - "1883"
        - "9001"
    ports:
        - "1883:1883"
        - "9001:9001"
````

First of all, I successfully created a new entity using the following code :

````
curl -iX POST \
  'http://localhost:9090/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:WaterQualityObserved:waterqualityobserved:Sevilla:D1",
    "type": "WaterQualityObserved",
    "temperature": {
        "type": "Property",
        "value": 24.4
    },
    "pH": {
        "type": "Property",
        "value": 7.4
    },
    "@context":
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
}'
````
Secondly, I successfully registered the services at the IoT Agent using the following code :
````
curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: iot' \
  -H 'fiware-servicepath: /' \
  -d '{
"services": [
   {
     "apikey":      "FN1",
     "cbroker":     "http://scorpio:9090",
     "entity_type": "WaterQualityObserved",
     "resource":    "/iot/json",
     "attributes": [
                {
                    "name": "temperature",
                    "type": "Property",
                    "object_id": "t"
                },
                {
                    "name": "pH",
                    "type": "Property",
                    "object_id": "p"
                }
            ]
   }
]
}'
````

After that, I posted a request for device provisioning using the following code :

````
curl -iX POST 'http://localhost:4041/iot/devices' -H "Fiware-Service: iot" -H "Fiware-ServicePath: /" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
    "devices": [
        {
            "apikey": "FN1",
	    "device_id": "sensor01",
            "entity_name": "urn:ngsi-ld:WaterQualityObserved:waterqualityobserved:Sevilla:D1",
            "entity_type": "WaterQualityObserved",
	    "protocol": "IoTA-JSON",
            "transport": "MQTT",
            "attributes": [
              {
                "name": "temperature",
                "type": "Property"
              },
              {
                "name": "pH",
                "type": "Property"
		
              }
            ]
        }
    ]
}' 
````

device is not created due to : 

time=2020-03-27T19:30:20.100Z | lvl=DEBUG | corr=95ff8e92-02b1-47d1-8ad0-874a330352c1 | trans=95ff8e92-02b1-47d1-8ad0-874a330352c1 | op=IoTAgentNGSI.DeviceService | srv=iot | subsrv=/ | msg=executeWithSecurity | comp=IoTAgent
scorpio_1    | 2020-03-27 19:30:20.270  INFO 9 --- [nio-9090-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
scorpio_1    | 2020-03-27 19:30:20.270  INFO 9 --- [nio-9090-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
scorpio_1    | 2020-03-27 19:30:20.295  INFO 9 --- [nio-9090-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 25 ms
fiware-iot-agent | time=2020-03-27T19:30:20.535Z | lvl=ERROR | corr=95ff8e92-02b1-47d1-8ad0-874a330352c1 | trans=95ff8e92-02b1-47d1-8ad0-874a330352c1 | op=IoTAgentNGSI.DeviceService | srv=iot | subsrv=/ | msg=Protocol error connecting to the Context Broker [404]: [object Object] | comp=IoTAgent
fiware-iot-agent | time=2020-03-27T19:30:20.535Z | lvl=DEBUG | corr=95ff8e92-02b1-47d1-8ad0-874a330352c1 | trans=95ff8e92-02b1-47d1-8ad0-874a330352c1 | op=IoTAgentNGSI.DeviceProvisioning | srv=iot | subsrv=/ | msg=Device provisioning failed due to the following error:  | comp=IoTAgent Error accesing entity data for device: sensor01 of type: WaterQualityObserved
fiware-iot-agent | time=2020-03-27T19:30:20.536Z | lvl=DEBUG | corr=95ff8e92-02b1-47d1-8ad0-874a330352c1 | trans=95ff8e92-02b1-47d1-8ad0-874a330352c1 | op=IoTAgentNGSI.GenericMiddlewares | srv=iot | subsrv=/ | msg=Error [ENTITY_GENERIC_ERROR] handling request: Error accesing entity data for device: sensor01 of type: WaterQualityObserved | comp=IoTAgent
fiware-iot-agent | time=2020-03-27T19:30:20.537Z | lvl=DEBUG | corr=95ff8e92-02b1-47d1-8ad0-874a330352c1 | trans=95ff8e92-02b1-47d1-8ad0-874a330352c1 | op=IoTAgentNGSI.DomainControl | srv=iot | subsrv=/ | msg=response-time: 448 | comp=IoTAgent
