### ISSUE TITLE
The agent does not send data to the Orion Context Broker with a request payload of 566 KB

### ISSUE THREAD

**Issue by ludilorenz** [telefonicaid/iotagent-json#827]
### IoT Agent JSON version the issue has been seen with

3.2.0

### Bound or port used (API interaction)

Northbound (Provision API and NGSI Interactions)

### NGSI version

NGSIv2, NGSI-LD

### Are you running a container?

Yes, I am using a contaner (Docker, Kubernetes...)

### Image type

normal

### Expected behaviour you didn't see

Sending data from the agent to the Context Broker and subsequent creation/update of the entity

### Unexpected behaviour you saw

Orion does not receive the request (there are no logs from Orion) and an error code 500 is returned with the following message: 

   {
      "name": "PayloadTooLargeError",
      "message": "request entity too large"
   }

### Configs

    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongodb
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagent-json-v2
      - IOTA_HTTP_PORT=7896
      - IOTA_PROVIDER_URL=http://iot-agent-v2:4041
      - IOTA_DEFAULT_RESOURCE=/iot/json

### Log output

```sh
2024-05-06 11:56:09 time=2024-05-06T09:56:09.245Z | lvl=DEBUG | corr=3951c9c6-1404-4c14-b204-e3cc2942c8e5 | trans=3951c9c6-1404-4c14-b204-e3cc2942c8e5 | op=IOTAJSON.HTTP.Binding | from=n/a | srv=fpn | subsrv=/FP4/battery_metrics | msg=Error PayloadTooLargeError handling request: request entity too large | comp=IoTAgent
2024-05-06 11:56:09 time=2024-05-06T09:56:09.842Z | lvl=DEBUG | corr=09b1fb75-89fc-4418-9e02-a9d516ec0902 | trans=09b1fb75-89fc-4418-9e02-a9d516ec0902 | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=fpn | subsrv=/FP4/battery_metrics | msg=Request for path [/iot/about] query [{}] from [localhost:4041] | comp=IoTAgent
2024-05-06 11:56:09 time=2024-05-06T09:56:09.842Z | lvl=DEBUG | corr=09b1fb75-89fc-4418-9e02-a9d516ec0902 | trans=09b1fb75-89fc-4418-9e02-a9d516ec0902 | op=IoTAgentNGSI.DomainControl | from=n/a | srv=n/a | subsrv=n/a | msg=response-time: 1 | comp=IoTAgent
```

**Comment by fgalan** [comment]
> msg=Error PayloadTooLargeError handling request: request entity too large

could be due to ContextBroker, as seen here

https://github.com/telefonicaid/fiware-orion/blob/5fe943b970599949e8f769bf7750e0e01f312edc/src/lib/rest/HttpStatusCode.cpp#L46

However, ContextBroker limits requests to 1MB size (see https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/user/known_limitations.md#request-maximum-size) and the size mentioned in the issue is smaller (566KB). Could you provide the 566KB request you are using in curl format, please (maybe with a link to https://pastebin.com)?

In addition, increasing the log level in Orion to INFO level may provide extra info (this link may be useful: https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/admin/management_api.md#log-configs-and-trace-levels)

**Comment by fgalan** [comment]
I'm removing the "bug" label due to this is (by the moment) expected behaviour.

**Comment by fgalan** [comment]
In addition, could you provide the docker-compose.yml you are using, please? It may be needed.

**Comment by ludilorenz** [comment]
> In addition, could you provide the docker-compose.yml you are using, please? It may be needed.

This is the docker-compose.yml I am using:

```
version: "3.1"
name: "dacapo_dummy_middleware"

services:

  iot-agent-v2:
    image: fiware/iotagent-json:3.2.0
    hostname: iot-agent-v2
    container_name: fiware-iot-agent-v2
    depends_on:
      - mongodb
    expose:
      - "4041"
      - "7896"
    ports:
      - "4041:4041"
      - "7896:7896"
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongodb
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagent-json-v2
      - IOTA_HTTP_PORT=7896
      - IOTA_PROVIDER_URL=http://iot-agent-v2:4041
      - IOTA_DEFAULT_RESOURCE=/iot/json
      
  mongodb:
    image: mongo:4.2
    hostname: mongodb
    container_name: mongo-db
    ports:
      - "27017:27017"
    command: --bind_ip_all 
    volumes:
      - mongo-db:/data/db
      - mongo-config:/data/configdb

  orion:
    image: fiware/orion:3.11.0
    hostname: 27017
    container_name: fiware-orion
    depends_on:
      - mongodb
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel INFO

volumes:
  mongo-db: ~
  mongo-config: ~
  synchdata: ~
```
